# Build

dest: _gh_pages
assets: <%= site.dest %>/assets


# Site metadata
title: Blog
lead: false
description: >
  "Blog theme and boilerplate, for Assemble."

# License info
license:
  type: MIT License
  url: ./license/index.html

# URLs
blog: http://upstage.github.io/assemble-blog-theme
repo: https://github.com/upstage/assemble-blog-theme
download:
  source: <%= site.repo %>/archive/master.zip


# SEO/SEM
google_analytics: false
google_site_id:   false


# Comments
disqus:
  shortname: assemble-blog-theme


# Social
social:
  twitter:
    via: jonschlinkert
    username: assemble
  facebook: false
  gplus: false
  hn: false
  google: false


# Sharing
social:
  twitter: false
  facebook: false
  gplus: false
  hn: false
  google: false


